### PR TITLE
Added Overwrite Course Configuration along with others

### PR DESCRIPTION
**Pull request by philcali**
It turns out that Moodle has two other options, namely: _Keep current roles and enrolments_ and _Keep current groups and groupings_.

As it turns out, setting these settings correctly closes a separate issue: issue #7.

### CODE REVIEW

**Comment by philcali** [comment]
I made the wrong issue reference in the commit... whoops

**Comment by rrusso** [comment]
How does this fix #17?

**Comment by philcali** [comment]
It applies the overwrite course config admin option for every restore. It defaults to _Yes_.

**Comment by rrusso** [comment]
I see that looking at the diff. Thanks.

**Comment by philcali** [comment]
if you wanted to see where it happens in the restore process, it's here:

https://github.com/lsuits/simple_restore/blob/master/lib.php#L230

This code needn't be changed.

**Comment by philcali** [comment]
I see no reason to delay merging this pull request.  I've tested the configurable features, and it appears to work as expected. I'm going to merge it in.

**Pull request merged**
