### PR TITLE
Backadel integration

### PR DESCRIPTION
**Pull request by philcali**
@adamzap, please review the integration piece.

Thanks.

### CODE REVIEW

**Comment by philcali** [comment]
It is important to note some changes from 1.9 -> 2.0:
1. The admin search on course shortname is a little different, because shortnames will be different.
2. The admin search is backward compatible with 1.9 backadel backups.

It just part of the admin to be mindful of the differences: Spaces and slashes will be translated to '-'. That's pretty much it though.

**Comment by adamzap** [comment]
This looks pretty straightforward...but the ternary on line 76 of list.php is a little offensive...

**Comment by philcali** [comment]
My feelings on the matter are mutual, but php does not support conditional that return, ie:

I would have preferred to have written it thusly:

```
$crit = if ($is_admin) {
  simple_restore_utils::backadel_shortname($shortname);
} else {
  simple_restore_utils::backadel_criterion($course);
}
```

Duping the left hand side of assignment statement is an unnecessary evil.

**Comment by adamzap** [comment]
It's only duplicated in code, not in execution. It's more readable that way.

**Comment by philcali** [comment]
> It's only duplicated in code, not in execution.

That's what I think is the unnecessary evil. I think a single 150 character line is far more offensive.

So multi-line ternary's are out of the question, then?

**Comment by adamzap** [comment]
Yeah...I don't like them. Might as well use an if in that situation.

This looks good though. Proceed otherwise.

**Pull request merged**
