### PR TITLE
Safer conversion with setting checks.

### PR DESCRIPTION
**Pull request by philcali**
Teachers were able to restore from backadel backups OK. The student data thing might be a separate issue.

@adamzap, can you review the code when you have a chance.
@rrusso, can you verify that a non-student data archive works?

In the meantime I'll start testing student data.

### CODE REVIEW

**Comment by philcali** [comment]
So, after beating my head on this for a couple of hours, I've finally come to the conclusion that Moodle has made restoring a back'ed up archive permission hell. This is a core Moodle problem, waaaaaay beyond the scope of simple restore.

I was mainly experimenting with quizzes, and here's some pretty awesome (I mean horrible) _features_ I found:
1. Whoever is capable of restoring questions has ownership of the quiz in a course. This means if Buddy restores a course with a quiz an instructor's course... The instructor can't edit the quiz because Buddy owns it! There's a neat check on ownership done _during restore_ which will totally explode the restore process. This can be replicated in stand alone Moodle.
2. An instructor is capable of _locking himself out_ by doing a regular restore. I think that's pretty neat.
3. This probably exists with other activities that use permission checks, which is probably all of them.

Here's the question capability code in question:

```
if (array_search($cap, $question_questioncaps)!== FALSE){
    if (!has_capability('moodle/question:'.$cap.'all', $context)){
        if ($question->createdby == $USER->id){
                  return has_capability('moodle/question:'.$cap.'mine', $context);
              } else {
                  return false;
              }
          } else {
              return true;
          }
      } else {
          return has_capability('moodle/question:'.$cap, $context);
      }
```

**Comment by rrusso** [comment]
I don't see this issue here.

### Steps I've taken to reproduce
1. Create a quiz with questions as Robert Russo (system admin)
2. Log in as Katina Test (Teacher in a course)
3. Edit quiz and re-order questions (works fine)
4. Edit question within quiz (works fine and shows Katina under last modified by)

What file does the check for ownership on restore?

I found backup/util/dbops/restore_dbops.class.php and that is not as strict as above and should allow anyone who has the capability to add questions and manage question categories to restore quizzes and questions without incident.

My head hurts too.

### Edit:

It looks like you are looking in lib/questionlib.php.

**Comment by philcali** [comment]
`question_has_capability_on` in lib/questionlib.php is called in the restore process, when overwriting a course. When it begins removing content from a course, it starts to make sure the user calling the restore that is removing stuff is capable of edit a quiz, **and then**  makes sure the user is the owner of those questions denoted by the following lines:

```
if ($question->createdby == $USER->id){
   return has_capability('moodle/question:'.$cap.'mine', $context);
} else {
   return false;
}
```

I am able to reproduce the following way:
1. Log-in as Kattest (Teacher in course), create quiz, questions, etc
2. Log-in as sysadmin, run backadel on the course.
3. Copy backadel archive to your machine (I copied it to web accessible location, and downloaded it).
4. Log-in as Kattest, upload archive, restore from archive (overwrite contents), and click through options...

You should be greeted with giant red exception, stating: "Sorry, but you do not currently have permissions to do that (edit)"

I get this using both restore processes.

It get's better:
1. Log in as sysadmin
2. _full_ restore the course from backadel archive (users, logs, blamo)
3. Log in as Kattest

She is unable to edit the question in the quiz, which clearly belong to her!

AFAIK, I'm using default caps on editingteacher.

**Comment by rrusso** [comment]
Where is question_has_capability_on called?

I just grepped all of the backup folder and came up empty.

**Comment by philcali** [comment]
Ha, that's the beauty of it! It's stack trace actually begins in moodlelib.php, in the function `remove_course_content`, and into `question_delete_course`, then `question_delete`, which will eventually call `question_has_capability_on`. Somewhere in the restore process `remove_course_content` is called.

**Comment by philcali** [comment]
I'm making a reference to the Moodle tracker ticket which contains the improvement code that allows instructors to overwrite materials on a restore: http://tracker.moodle.org/browse/MDL-29988

I'm interested in hearing the feedback.

**Comment by rrusso** [comment]
Your changes here work fine in 2.2 as an instructor.

Thanks.

**Pull request merged**
