### PR TITLE
Stricter username searches in filenames.

### PR DESCRIPTION
**Pull request by philcali**
@rrusso, I this will solve the problem at hand.

### CODE REVIEW

**Comment by rrusso** [comment]
6067212 is totally broken.

**Comment by philcali** [comment]
That is valid regex, but I think I need to explicitly escape the period anyway (even though most regex engines will auto escape inside the brackets).

**Comment by philcali** [comment]
I'll go ahead and merge this one in. And we'll discuss possibly cutting out the admin shortname filter options from the program in a separate issue.

**Comment by rrusso** [comment]
Sounds great!

**Pull request merged**
